// This file was generated by PermissionsDispatcher. Do not modify!
package com.timursoft.imtranslator;

import android.support.v4.app.ActivityCompat;

import permissions.dispatcher.PermissionUtils;

final class MainActivityPermissionsDispatcher {
  private static final int REQUEST_SHOWFILEPICKER = 0;

  private static final String[] PERMISSION_SHOWFILEPICKER = new String[] {"android.permission.READ_EXTERNAL_STORAGE","android.permission.WRITE_EXTERNAL_STORAGE"};

  private MainActivityPermissionsDispatcher() {
  }

  static void showFilePickerWithCheck(MainActivity target) {
    if (PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWFILEPICKER)) {
      target.showFilePicker();
    } else {
      ActivityCompat.requestPermissions(target, PERMISSION_SHOWFILEPICKER, REQUEST_SHOWFILEPICKER);
    }
  }

  static void onRequestPermissionsResult(MainActivity target, int requestCode, int[] grantResults) {
    switch (requestCode) {
      case REQUEST_SHOWFILEPICKER:
      if (PermissionUtils.getTargetSdkVersion(target) < 23 && !PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWFILEPICKER)) {
        return;
      }
      if (PermissionUtils.verifyPermissions(grantResults)) {
        target.showFilePicker();
      }
      break;
      default:
      break;
    }
  }
}
